server {
    listen 80;

    # Définit le répertoire racine où se trouvent les fichiers de l'application
    root /usr/share/nginx/html;

    # Fichier d'index par défaut
    index index.html index.htm;

    # Configuration pour les applications Angular
    # Tente de servir le fichier demandé, puis si non trouvé, renvoie index.html
    # C'est crucial pour que les routes Angular fonctionnent correctement après un rafraîchissement
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache statique pour les fichiers assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|eot|ttf|woff|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Ne pas cacher les fichiers HTML pour permettre les mises à jour
    location ~* \.(html)$ {
        expires -1;
        add_header Cache-Control "no-cache";
    }
}
